### ISSUE TITLE
Add a popup modal for users to confirm their currency choice the first time they visit a store

### ISSUE THREAD

**Issue by DarraghJC-zz** [DarraghJC/gist-test#1]
**Theme:** Debut

**Version(s) successfully tested on:** 12.2.1

**Recommended design time:** 15 minutes

**Tags:** Debut, Sectioned

----

**Note**:
> This requires a user to already have multiple currencies enabled on their store, have at least 2 currencies on their storefront and are using Shopify Payments.
Our help doc on [selling in multiple currencies](https://help.shopify.com/en/manual/payments/shopify-payments/multi-currency) contains more information on this.

## What you have
![](https://screenshot.click/ppwu0hi19llo08ck30z99mh.png)
When a user visits a store with multiply currencies, the currency defaults to the store default currency.

## What you want
![](https://screenshot.click/kusk9hi19llo08ck30jwcal.png)
A modal popup that shows the first time a user vists the store prompting them to select their currency from the available options.

----

## What you do

**Step 1:**
Add a new snippet called `currency-popup.liqiud` and paste the following code.

```html
<script src="{{ 'currency.js' | asset_url }}" defer="defer"></script>

<div id="CurrencyModal" class="modal modal--currency" role="dialog" aria-modal="true" aria-labelledby="currency-modal-heading">
  <div class="modal__inner">
    <div class="modal__centered--currency password-modal__content page-width">
      <div class="modal-currency-content text-center">
        <h2 class="password__form-heading h4" id="password-modal-heading">{{ 'general.currency.modal_heading' | t }}</h2>
        {% form 'currency', class: "currency-selector currency-selector--modal" %}
        <div class="input-group">
          <label for="CurrencySelector" class="visually-hidden">{{ 'general.currency.dropdown_label' | t }}</label>
          <div class="currency-selector__input-wrapper select-group currency-selector__input-wrapper--modal">
            <select name="currency" id="CurrencySelector-modal" class="currency-selector__dropdown currency-selector__dropdown--modal" aria-describedby="a11y-refresh-page-message a11y-selection-message" data-currency-selector>
              {% for currency in shop.enabled_currencies %}
              <option value="{{currency.iso_code}}"{% if currency == cart.currency %} selected="true"{% endif %}>{{currency.iso_code}}</option>
              {% endfor %}
            </select>
            {% include 'icon-chevron-down' %}
          </div>
          <span class="input-group__btn">
            <button type="submit" name="commit" class="btn btn--narrow currency-modal--confirm js-currency-modal--close">Submit</button>
          </span>
        </div>
        {% endform %}
      </div>
    </div>
  </div>
</div>

```

**Step 2:** 

Create a new asset file called `currency.js` and paste the following code (adapted from `password.js`)

```js
window.Modals = (function() {
  function Modal(id, name, options) {
    var defaults = {
      close: '.js-currency-modal--close',
      open: '.js-modal-open-' + name,
      openClass: 'modal--is-active'
    };

    this.$modal = $('#' + id);

    if (!this.$modal.length) {
      return false;
    }

    this.nodes = {
      $parent: $('html').add('body')
    };
    this.config = $.extend(defaults, options);

    this.modalIsOpen = false;
    // eslint-disable-next-line shopify/jquery-dollar-sign-reference
    this.$focusOnOpen = this.config.focusOnOpen
    ? $(this.config.focusOnOpen)
    : this.$modal;
    this.init();
  }

  Modal.prototype.init = function() { 
    $(this.config.open).on('click', $.proxy(this.open, this));
    this.$modal.find(this.config.close).on('click', $.proxy(this.close, this));
  };

  Modal.prototype.open = function(evt) {
    // Keep track if modal was opened from a click, or called by another function
    // don't open an opened modal
    if (this.modalIsOpen) {
      return;
    }

    this.$modal.addClass(this.config.openClass);
    this.nodes.$parent.addClass(this.config.openClass);

    this.modalIsOpen = true;

    const focusForm = document.querySelector('.currency-selector__dropdown--modal');
    focusForm.focus();


    this.bindEvents(); 
  };

  Modal.prototype.close = function() {
    // don't close a closed modal
    if (!this.modalIsOpen) {
      return;
    }

    // deselect any focused form elements
    $(document.activeElement).trigger('blur');

    this.$modal.removeClass(this.config.openClass);
    this.nodes.$parent.removeClass(this.config.openClass);

    this.modalIsOpen = false;

    // Remove focus on modal
    slate.a11y.removeTrapFocus({
      $container: this.$modal,
      namespace: 'modal_focus'
    });

    this.unbindEvents();
  };

  Modal.prototype.bindEvents = function() {
    // Pressing escape closes modal
    this.nodes.$parent.on(
      'keyup.modal',
      $.proxy(function(evt) {
        if (evt.keyCode === 27) {
          handleSubmit();
          this.close();
        }
      }, this)
    );
  };

  Modal.prototype.unbindEvents = function() {
    this.nodes.$parent.off('.modal');
  };

  return Modal;
})();

const removeModal = () => {
  const modal = document.querySelector('#CurrencyModal');
  modal.parentNode.removeChild(modal);
}

const handleSubmit = () => {
  const currencySettings = {
    currencyChosen: "true"
  }
  // set localStorage to save that user has made a choice
  localStorage.setItem('currencyStorage',  JSON.stringify(currencySettings));
}

$(function() {
  const currencyModalForm = document.querySelector('.currency-selector__dropdown--modal');
  const confirmDefault = document.querySelector('.currency-modal--confirm');
  // Listen for form being submitted
  confirmDefault.addEventListener('click', handleSubmit);
  // Create modal to allow user to choose currency

  const currencyStorage = JSON.parse(localStorage.getItem('currencyStorage'));
  // User has not previously selected currency on this store
  if(currencyStorage === null) {
    const currencyModal = new window.Modals('CurrencyModal', 'currency-modal', {
      focusOnOpen: '#CurrencySelector-modal'
    });
    // show currency popup and form4
    currencyModal.open();
  } else {
    // removeModal to prevent id conflicts with default currency form
    removeModal();
  }
});
```

**Step 3:**

Open the `en.default.json` Locales files, and find the following code:

```js
    "currency": {
      "dropdown_label": "Currency"
    }
```

and add the following `, "modal_heading": "Please select your currency."`, giving you:

```js
    "currency": {
      "dropdown_label": "Currency",
\!h      "modal_heading": "Please select your currency."
    }
```

**Step 4:**

Open `theme.js` and find the following code; `$(selectors.multicurrencySelector).on('change', function() {` and wrap the following code in an if statement:

```js
     $(this)
        .parents('form')
        .submit();
```

giving you:

```js
\!h     if(!this.classList.contains('currency-selector__dropdown--modal')){
        $(this)
        .parents('form')
        .submit();
\!h      }

```

**Step 5:**

Add the following to the bottom of `theme.scss.liquid`:

```css
#CurrencyModal.modal--is-active {
  z-index: 999;
} 

.modal__centered--currency {
  -ms-transform: translateY(-50%);
  -webkit-transform: translateY(-50%);
  transform: translateY(-50%);
  position: relative;
  top: 20%;
  display: grid;
  justify-content: center;
}

.currency-selector--modal {
  margin: 0 auto;
  width: 200px;
  margin-bottom: 20px;
  @include media-query($small) {
    padding: 0;
  }
}

.currency-selector__input-wrapper--modal {
  border: 1px solid #949494;
  background-color: #fff;
  color: #000;
  max-width: 100%;
  line-height: 1.2;
  border-radius: 2px 0 0 2px;
  width: 120px;
  margin-top: 0;
}

.modal--currency {
  background-color: rgba(255, 255, 255, 0.95);
}

.currency-selector__dropdown--modal {
  width: 100%;
  padding-top: 12px;
  padding-bottom: 12px;
}

.modal-currency-content {
  padding: 60px;
  opacity: 1;
  background-color: #fefefe;
  -webkit-box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
  box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
}    

#CurrencyModal .input-group {
  flex-wrap: nowrap;
}
```

**Step 6:**

Open `theme.liquid` and add the following code below `{% section 'header %}`:

```
  {% if shop.enabled_currencies.size > 1 %}
    {% include 'currency-popup' %} 
  {% endif %} 
```

----

**Additional notes:** 

This gist uses localStorage to save the user's choice in their browser, so they won't be prompted to choose their currency again after the first visit (or until their clear their cache).

When testing - you can remove the localStorage object `currencyStorage` to make the modal appear again in Chrome DevTools' `Application` tab:
![](https://screenshot.click/qbiykhi19llo08ck303vand.png)
