### ISSUE TITLE
Turn the Debut slideshow link into a CTA button

### ISSUE THREAD

**Issue by DarraghJC-zz** [DarraghJC/gist-test#3]
**Theme:** Debut

**Version(s) successfully tested on:** 9.0.0

**Recommended design time:** 

**Reviewed by:**

----

## What you have
![](https://screenshot.click/02-22-c4y8n-4valt.png) 

## What you want
![](https://screenshot.click/02-18-iwwhv-9dlsg.png) 

----

## What you do

**Step 1:**

Open the **slideshow.liquid** section and comment out the following code:
(It's just after `<div class="slideshow__slide slideshow__slide--{{ block.id }}{% if is_background_video %}...`)

``` liquid
{% if block.settings.link != blank %}
  <a href="{{ block.settings.link }}" class="slideshow__link">
{% endif %}
```

Find and comment out the closing `</a>` tag and surrounding if statement:

```liquid
{% if block.settings.link != blank %}
  </a>
{% endif %}
```

Before the closing `</div>` for `<div class="slideshow__text-content">` add the following:

```liquid
{% if block.settings.link != blank %}
<a href="{{ block.settings.link }}" class="slideshow__link">
  <div class="slideshow__link--inner">
 {{ block.settings.link_text }}
  </div>
</a>
{% endif %}
```

This is combining the code we previously commented out, and added the custom button text div, giving you:

![](https://screenshot.click/02-37-rl21o-lolrv.png) 

**Step 2:**

Add the following settings to the image block schema to allow the merchant to select the text that will appear.

```json
  {
    "type": "text",
    "id": "link_text",
    "label": "The text for your slide's button",
    "default": "Shop Now"
  }
```

**Step 3:**

Open `settings_schema.json` and add the following to the Colors/Button settings to allow the merchants to choose their own colours"

```json
  {
    "type": "color",
    "id": "slide_button_bg",
    "label": "Slideshow Button Background",
    "default": "#fff"
  },
  {
    "type": "color",
    "id": "slide_button_text",
    "label": "Slideshow Button Text",
    "default": "#000"
  }
```

Giving you:

![](https://screenshot.click/02-34-1py7r-kcewx.png) 
**Step 4:**

Add the followng to the bottom of `theme.scss.liquid`

```css
.slideshow__link {
  display: flex;
  position: absolute;
  top: 180px;
  bottom: 0;
  width: 100%;
  align-items: center;
  justify-content: center;
  z-index: 10;
  &:hover {
   opacity: 1; 
  }
}
 
.slideshow__link--inner {
  padding: 18px 36px; 
  background: {{ settings.slide_button_bg }};
  color: {{ settings.slide_button_text }};
  text-transform: uppercase;
  font-weight: 700;
}

@include media-query($small) {
  .slideshow__text-content {
    top: 33%;
  }
  .slideshow__link--inner {
    padding: 12px 26px;
  }
}
```
----
Done!
**Additional notes:** 

**Alternative keywords:**
